services:
  golang: &golang
    build:
      context: ../
      dockerfile: ./compose/development/golang/Dockerfile
    image: microsaas_dev_golang
    container_name: golang
    # depends_on:
    #   - postgres
    volumes:
      - .:/app:z
    env_file:
      - ../.envs/.development/.golang
      - ../.envs/.development/.postgres
    ports:
      - "8000:8000"
    command: /start
    # labels:
